/*
 * existingApis
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.feguiluz.backenddevtest.client.api;

import com.feguiluz.backenddevtest.client.model.ProductDetail;
import java.util.Set;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * Gets a product detail
     *
     * Returns the product detail for a given productId
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProductProductIdTest() {
        String productId = null;
        ProductDetail response = api.getProductProductId(productId);

        // TODO: test validations
    }
    
    /**
     * Gets the ids of the similar products
     *
     * Returns the similar products to a given one ordered by similarity
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProductSimilaridsTest() {
        String productId = null;
        Set<String> response = api.getProductSimilarids(productId);

        // TODO: test validations
    }
    
}
